apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      - system:nodes
      rolearn: arn:aws:iam::632358182060:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::632358182060:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-155W1BKRU59GF
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-02T10:32:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1487"
  uid: 3e4a6943-a547-4706-a37f-24ff29ba94e8
